gnuplot scripts/1_2_beach.gs > plots/1_2_beach.gif
#gnuplot scripts/1_2_beach_linear_eq.gs > plots/1_2_beach_linear_eq.gif
#gnuplot scripts/1_2_beach_equalized.gs > plots/1_2_beach_equalized.gif
gnuplot scripts/1_2_skyline.gs > plots/1_2_skyline.gif
#gnuplot scripts/1_2_skyline_linear_eq.gs > plots/1_2_skyline_linear_eq.gif
#gnuplot scripts/1_2_skyline_equalized.gs > plots/1_2_skyline_equalized.gif
gnuplot scripts/1_3_ref.gs > plots/1_3_ref.gif
gnuplot scripts/1_3_sfx.gs > plots/1_3_sfx.gif
gnuplot scripts/1_3_park.gs > plots/1_3_park.gif
gnuplot scripts/1_4_gaussian.gs > plots/1_4_gaussian.gif
open -a Preview plots/1_2_beach.gif
#open -a Preview plots/1_2_beach_linear_eq.gif
#open -a Preview plots/1_2_beach_equalized.gif
open -a Preview plots/1_2_skyline.gif
#open -a Preview plots/1_2_skyline_linear_eq.gif
#open -a Preview plots/1_2_skyline_equalized.gif
open -a Preview plots/1_3_ref.gif
open -a Preview plots/1_3_sfx.gif
open -a Preview plots/1_3_park.gif
open -a Preview plots/1_4_gaussian.gif